services:
    app:
        build:
            context: ./docker/8.2
            args:
                WWWGROUP: '${WWWGROUP}'
        container_name: memory_book_app
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '127.0.0.1:${BACK_PORT:-8089}:80'
            - '127.0.0.1:${REVERB_PORT:-8082}:${REVERB_PORT:-8081}'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - ./:/app
        networks:
            - memory_book

    postgres:
        image: postgres:latest
        container_name: memory_book_db
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
        ports:
            - '5436:5432'
        volumes:
            - memory_book_data:/var/lib/postgresql/data
        networks:
            - memory_book


networks:
    memory_book:
        name: memory_book
        external: false

volumes:
    memory_book_data:
