services:
    app:
        build:
            context: ./docker/8.2
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '127.0.0.1:${BACK_PORT:-8088}:80'
            - '127.0.0.1:${REVERB_PORT:-8081}:${REVERB_PORT:-8081}'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - ./:/app
        networks:
            - aa_oren

    postgres:
        image: postgres:latest
        container_name: aaoren_db
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
        ports:
            - '5437:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - aa_oren


networks:
    aa_oren:
        name: aa_oren
        external: false

volumes:
    postgres_data:
