/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuctionStatus: typeof import('./src/components/auction/AuctionStatus.vue')['default']
    BlockViewer: typeof import('./src/components/BlockViewer.vue')['default']
    CategoryStatusMessage: typeof import('./src/components/learning/CategoryStatusMessage.vue')['default']
    DocumentDropZone: typeof import('./src/components/document/DocumentDropZone.vue')['default']
    DocumentPanel: typeof import('./src/components/document/DocumentPanel.vue')['default']
    DocumentsTable: typeof import('./src/components/document/DocumentsTable.vue')['default']
    DocumentsViewPanel: typeof import('./src/components/document/DocumentsViewPanel.vue')['default']
    ElDate: typeof import('./src/components/ElDate.vue')['default']
    ElMaskInput: typeof import('./src/components/ui/ElMaskInput.vue')['default']
    ElPhoneNumber: typeof import('./src/components/ui/ElPhoneNumber.vue')['default']
    FieldError: typeof import('./src/components/errors/FieldError.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    KiviCalendar: typeof import('./src/components/KiviCalendar.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LogoIcon: typeof import('./src/components/LogoIcon.vue')['default']
    RealtyLegalStatus: typeof import('./src/components/realty/RealtyLegalStatus.vue')['default']
    RealtyStatusElement: typeof import('./src/components/realty/RealtyStatusElement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadImageModal: typeof import('./src/components/cropper/UploadImageModal.vue')['default']
  }
}
